# Generated by Django 4.1.4 on 2023-01-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(choices=[('2013', '2013'), ('2014', '2014'), ('2015', '2015')], default='default', max_length=50),
        ),
    ]
