# Generated by Django 4.1.4 on 2023-01-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_car_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['name'], 'verbose_name': 'my cars'},
        ),
    ]
